### ISSUE TITLE
Ability to set azure cloud environment in terraform init

### ISSUE THREAD

**Issue by marcsteinert78** [jason-johnson/azure-pipelines-tasks-terraform#136]
I would need the possibilty to set the azure cloud environment for example to azure china cloud, so the task can create the storage account for the tf state files there.

az cloud set --name AzureChinaCloud 

would be the necessary step before the az login that happens before the resources for the remote backend are created

**Comment by marcsteinert78** [comment]
I can bypass the issue by running az cloud set ... in a previous task as a workaround

**Comment by charleszipp** [comment]
If you are already using an .env file with the task you can also use the [ARM_ENVIRONMENT](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#argument-reference) to configure the appropriate cloud. This can also be set on the azurerm provider configuration itself in your terraform hcl. Others I have helped have made use of the environment variable option for government and china cloud environments.
