### ISSUE TITLE
New Feature Request: Allow Hiding of Plan Summary (Warnings)

### ISSUE THREAD

**Issue by hramos05** [jason-johnson/azure-pipelines-tasks-terraform#137]
We run multiple plans during a build, and this causes a "page" of warnings.

It would be great if we can have a "switch" to turn them off on both the Plan & Show commands (or make it info instead?)

**Comment by jason-johnson** [comment]
On the summary screen there is an `Error` button to filter to only the errors.  It would require touching a lot of places to make warnings optional.  What is the use case that these warnings can't be fixed instead of suppressed?

**Comment by jason-johnson** [comment]
Unless there is a very strong case, this isn't something we will be adding to the tool.
