### ISSUE TITLE
Support for AzureRM Service Connections that have Management Group Scope

### ISSUE THREAD

**Issue by liamfoneill** [jason-johnson/azure-pipelines-tasks-terraform#20]
As an Azure Administrator, I have many subscriptions grouped together under management groups. I have created a Service Connection in Azure DevOps has a scope defined at a particular management group scope (instead of subscription). This allows me to avoid creating a separate service principal and service connection for every subscription I create. Least privilige is acheived by only grouping subscriptions together in a management group that I am comfortable having a single service principal with 'Contributor' rights over.

However in the task, when I select my service connection that has management group contributor permissions I do not have the ability to select the subscription which contains the storage account for my Terraform State storage. 

Request: Add an additional field to select the subscription if an AzureRM service connection is selected that has Management group-level permissions. If you add this feature, yours will be the only Terraform extension on the marketplace that has it.

![image](https://user-images.githubusercontent.com/1243172/108488356-31bd0a00-7298-11eb-9898-42b36986d8e8.png)
![image](https://user-images.githubusercontent.com/1243172/108488450-4f8a6f00-7298-11eb-866f-48de8b8cd5ff.png)

**Comment by charleszipp** [comment]
Seeing requests on the DevLabs version for this as well
![image](https://user-images.githubusercontent.com/4292559/148560698-c6004a27-bb5b-43c9-9a97-4c342fd2277b.png)

https://github.com/microsoft/azure-pipelines-extensions/issues/794

**Comment by charleszipp** [comment]
Looks like this is not even supported in the azure cli task still https://github.com/microsoft/azure-pipelines-tasks/issues/11151

**Comment by charleszipp** [comment]
Update see PR #243 for proposed implementation
