### ISSUE TITLE
output variables - similar to the MS Terraform extension

### ISSUE THREAD

**Issue by DenWin** [jason-johnson/azure-pipelines-tasks-terraform#34]
Provide output variables for the jsonPlanFilePath and jsonOutputVariablesPath similar to the MS Terraform task.
Additionally obviously the path to the publishPlan.

![image](https://user-images.githubusercontent.com/13867326/118808073-5b8ec880-b8a9-11eb-9148-2598e2de578b.png)

**Comment by charleszipp** [comment]
@DenWin could you share some more info on how you plan to use these files? Currently the task does support running `terraform output` and emits all output variables as pipeline variables. Why would you also need the file?

**Comment by DenWin** [comment]
E.g. I use this script to point out, which resources are actually effected, rather than a full plan:
![image](https://user-images.githubusercontent.com/13867326/118991351-f3f97b80-b983-11eb-947e-9898a60e3f1e.png)

Currently I help myself by knowing where the publishedplan file is been created and to use this path, but it would be nicer to get that information from the task itself. But I had to search for it 1st.

But you are right the output parameters are of no interest.

**Comment by DenWin** [comment]
the information whether `terraform plan` uses `-out=tfplan`, or to be specific, the name of this binary plan could also be of interest.
That way subsequent tasks could build on the fact, whether a plan exist or a publishedPlan exist

**Comment by DenWin** [comment]
ah, another reason, where I personally would use this information. If I could go by "publish if the filename is provided", it would reduce complexity.

```
    ###########################################################
    #                         Publish                         #
    ###########################################################
  - publish                               : $(workingDirectory)/$(planOutFile)
    condition                             : ${{ and( not( parameters.OnlyValidate ), ne( parameters.artifact, '' ) ) }}   # do not stop with Validation
    artifact                              : ${{ parameters.artifact }}
  - publish                               : $(workingDirectory)/${{ parameters.deployStage }}.publishPlanResults
    condition                             : ${{ and( not( parameters.OnlyValidate ), ne( parameters.artifact, '' ) ) }}   # do not stop with Validation
    artifact                              : ${{ parameters.artifact }}_publishPlanResults
  - publish                               : $(workingDirectory)/${{ parameters.deployStage }}.publishPlanResults
    condition                             : ${{ and( not( parameters.OnlyValidate ), eq( parameters.artifact, '' ) ) }}   # do not stop with Validation
    artifact                              : publishPlanResults
```

**Comment by charleszipp** [comment]
@DenWin thanks for the info. I have very intentionally tried to avoid this task exposing the plan in json form due to the fact that it could potentially expose secrets. This is why when this task runs terraform show and output it runs those silently (so the output isnt written to the build logs). Additionally the output of those are only held in memory (not written to disk) for the same reason.

However, the file generated for publishPlanResults respects the redaction that terraform performs so it does not carry the same risk. **If the task were to expose the path or url the publishPlanResults file as a pipeline variable would that satisfy what you need from this particular issue?**

**Comment by DenWin** [comment]
yeah, actually those were the once I would use.

**Comment by charleszipp** [comment]
Replaced with #37
