### ISSUE TITLE
Expose path or url to publishPlanResult files

### ISSUE THREAD

**Issue by charleszipp** [jason-johnson/azure-pipelines-tasks-terraform#37]
The content of the publishPlanResult file is useful in determining what resources are actually going to be changed. In some cases, users would like access to this file to parse the content and emit warnings for changes to critical infrastructure. Using this file for this purpose over the JSON output via `terraform show` is favored due to the fact it redacts sensitive values. The JSON output from show does not.

**Important:** This should also consider that multiple publishPlanResult files could be produced within a single pipeline. The solution should provide access to all published plans.

cc @DenWin Replacing #34 with this issue to focus on providing access to publishPlanResult files

**Comment by DenWin** [comment]
If for `terraform plan` the `-out`-argument is provided this path should be returned similarly to the publishPlanResult-file.

**Comment by jason-johnson** [comment]
I prefer the solution to have variables available in the pipeline.  These should not leak out so there is no issue with secrets.  So we won't do this one.
