### ISSUE TITLE
New Feature Request: Support TFE TF Cloud tokens

### ISSUE THREAD

**Issue by dmedeiros204** [jason-johnson/azure-pipelines-tasks-terraform#41]
**Describe the feature**
To access remote backends and a tfe module registry you must provide credentials. If we could populate this token as an option it would mean not having to create a secured file

credentials "app.terraform.io" {
  token = "xxxxxx.atlasv1.zzzzzzzzzzzzz"
}

https://www.terraform.io/docs/cli/config/config-file.html#credentials-1

Similar to this
https://github.com/hashicorp/setup-terraform/blob/9771d0c9cdc9b0d88429a5ed16417f3a0362fbde/lib/setup-terraform.js#L80

**Comment by jason-johnson** [comment]
Hi @dmedeiros204, how would propose this be done?  I believe you can already populate the tokens in the pipeline with environment variables to get the effect you want.

**Comment by jason-johnson** [comment]
Ok, I have not received a response and I do not see why terraformCli would be involved in this situation.  Every client I work with handles this in the pipeline via environment variables or SSH keys defined in the environments.

Please feel free to re-open with any additional information.
