### ISSUE TITLE
Order Plans by name in ADO UI

### ISSUE THREAD

**Issue by shep1987** [jason-johnson/azure-pipelines-tasks-terraform#56]
Any chance the plans dropdown could be ordered?

We can have multiple plans of the same resource with a stage number at the end and this would make it much easier too find the correct one.

EG

Plan-StageA-1
Plan-StageA-2
Plan-StageB-1

I think it could be done here but not worked with pipeline UI's before so not 100%!

https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/05b63e3915bacfe4f0ed39781bf6a68bc2ea43d9/views/terraform-plan/src/plan-summary-tab/plan-summary-tab.tsx#L43

**Comment by charleszipp** [comment]
That is one way that it could be ordered. The attachments that populate could also be ordered ahead of mapping to plan types [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/05b63e3915bacfe4f0ed39781bf6a68bc2ea43d9/views/terraform-plan/src/plan-summary-tab/plan-summary-tab.tsx#L38). If @shep1987 or anyone else would be interested in submitting a PR, I can help get this merged in.

**Comment by jason-johnson** [comment]
No responses for multiple years so closing for now.  It may be revisited in future during additional feature adding.
