### ISSUE TITLE
TerraformCLI does not support 'fmt' command as documented

### ISSUE THREAD

**Issue by someoneelsescloud** [jason-johnson/azure-pipelines-tasks-terraform#64]
**Describe the bug**
TerraformCLI task does not support 'fmt' command as documented. I manually installed the extension for Azure DevOps server but can confirm on the Microsoft hosted version also does not have the 'fmt' option either.

**To Reproduce**
1. Setup pipeline as YAML
2. Add a Task (via the assistant)
3. Select TerraformCLI
4. 'fmt' is not in the list (also manually writing the task in YAML, fmt is highlighted as an unsupported value)

**Expected behavior**
To be able to use the 'fmt' command to lint Terraform configuration files.

**Screenshots**

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: [e.g. ubuntu debian]
 - Hosted/Self Hosted
 - Terraform version used (Default for hosted agent is acceptable)
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**

**Comment by charleszipp** [comment]
@someoneelsescloud thanks for reporting this. It looks like all that needs to be modified is the [`task.json` file](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/4bbda7f0c4eaa06f1c91163329c6acc138f4304c/tasks/terraform-cli/task.json#L59) such that `"fmt":"fmt"` is added to the list of options. All the rest of the code is in place to support this command. If you or someone else would be interested in submitting a PR for this, I can help get it merged in so it can be used as the docs indicate.

**Comment by someoneelsescloud** [comment]
@charleszipp done https://github.com/charleszipp/azure-pipelines-tasks-terraform/pull/66

**Comment by charleszipp** [comment]
merged with #66. closing. Thanks @someoneelsescloud for the contribution!
